Integers = ("integers are whole numbers,and can be negative or positive.")
print(Integers)

Floats = ("float are negative or posotive numbers,which contains a decimal point in it.")
print(Floats)
Strings = ("strings are an aarrangement of one, or multiple characters")
print(Strings)
Boolean = ("represents scenarios with two outcomes.")
print(Boolean)
print("integres examples")
print (type(250))
print (type(-40))
print("float examples")
print (type(1.0))
print (type(-40.12))
print("strings examples")
print (type("How are you doing?"))
print (type("university of cambridge."))
print("boolean example")
print (type(False))
print  (type(True))
